name: nibbles
description: "Find Food Fast"
publish_to: "none"
version: 0.2.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  location: ^8.0.0
  flutter_secure_storage: ^8.0.0
  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.5.0
  dio: ^5.4.0
  google_sign_in: ^6.1.4
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  flutter_map_marker_popup: ^8.0.1
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  image_picker: ^1.1.2
  table_calendar: ^3.2.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: "^0.14.4"
  flutter_native_splash: ^2.4.6
  google_polyline_algorithm: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: "assets/launcher_icon.png"
  color: "#B83C5E"
  # branding: "assets/branding.png"
  # from android 12 splash screen is handled a bit diff
  android_12:
    image: "assets/launcher_icon.png"
    color: "#B83C5E"
    icon_background_color: "#B83C5E"
    # branding: "assets/branding.png"

  # If we want to create splash for web or ios need to modify here.
  ios: false
  web: false

flutter_launcher_icons:
  android: true
  image_path: "assets/launcher_icon.png"
  adaptive_icon_foreground: "assets/launcher_icon.png"
  adaptive_icon_background: "#B83C5E"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # If we want to create icon for web or ios need to modify here.
  ios: false
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/FindingNibbles.svg
    - assets/images/default_restaurant.jpg
    - assets/images/default_recipe.jpg
