/// Common ingredients list for autocomplete suggestions
class IngredientSuggestions {
  static const List<String> commonIngredients = [
    // Proteins - Meat
    'chicken breast',
    'chicken thighs',
    'chicken wings',
    'chicken drumsticks',
    'whole chicken',
    'ground chicken',
    'ground beef',
    'beef steak',
    'beef roast',
    'beef brisket',
    'beef ribs',
    'ground turkey',
    'turkey breast',
    'pork chops',
    'pork shoulder',
    'pork belly',
    'pork tenderloin',
    'ground pork',
    'bacon',
    'ham',
    'prosciutto',
    'pancetta',
    'chorizo',
    'italian sausage',
    'bratwurst',
    'lamb chops',
    'leg of lamb',
    'ground lamb',
    'veal',
    'duck',
    'duck breast',
    'venison',
    'rabbit',

    // Proteins - Seafood
    'salmon',
    'tuna',
    'cod',
    'halibut',
    'mahi mahi',
    'tilapia',
    'sea bass',
    'snapper',
    'sole',
    'flounder',
    'mackerel',
    'sardines',
    'anchovies',
    'trout',
    'catfish',
    'monkfish',
    'swordfish',
    'shrimp',
    'prawns',
    'lobster',
    'crab',
    'scallops',
    'mussels',
    'clams',
    'oysters',
    'squid',
    'octopus',
    'cuttlefish',

    // Proteins - Plant-based
    'eggs',
    'tofu',
    'tempeh',
    'seitan',
    'textured vegetable protein',
    'plant-based meat',
    'jackfruit',

    // Vegetables - Alliums
    'onion',
    'red onion',
    'white onion',
    'yellow onion',
    'sweet onion',
    'shallots',
    'green onions',
    'scallions',
    'chives',
    'garlic',
    'garlic scapes',
    'leek',

    // Vegetables - Nightshades
    'tomato',
    'cherry tomatoes',
    'roma tomatoes',
    'beefsteak tomatoes',
    'bell pepper',
    'red bell pepper',
    'yellow bell pepper',
    'orange bell pepper',
    'green bell pepper',
    'jalapeño',
    'serrano pepper',
    'habanero',
    'poblano pepper',
    'anaheim pepper',
    'chipotle pepper',
    'cayenne pepper',
    'thai chili',
    'banana pepper',
    'eggplant',
    'japanese eggplant',
    'potato',
    'red potato',
    'yukon potato',
    'russet potato',
    'fingerling potato',
    'sweet potato',
    'yam',

    // Vegetables - Brassicas
    'broccoli',
    'cauliflower',
    'brussels sprouts',
    'cabbage',
    'red cabbage',
    'napa cabbage',
    'bok choy',
    'kale',
    'collard greens',
    'mustard greens',
    'turnip greens',
    'arugula',
    'watercress',
    'radish',
    'daikon radish',
    'turnip',
    'rutabaga',
    'kohlrabi',

    // Vegetables - Root vegetables
    'carrot',
    'baby carrots',
    'parsnip',
    'beetroot',
    'golden beets',
    'jicama',
    'ginger',
    'fresh ginger',
    'galangal',
    'turmeric root',
    'horseradish',
    'wasabi',

    // Vegetables - Squash & Gourds
    'zucchini',
    'yellow squash',
    'butternut squash',
    'acorn squash',
    'delicata squash',
    'kabocha squash',
    'spaghetti squash',
    'pumpkin',
    'sugar pumpkin',
    'cucumber',
    'english cucumber',
    'persian cucumber',
    'pickling cucumber',

    // Vegetables - Greens
    'spinach',
    'baby spinach',
    'lettuce',
    'romaine lettuce',
    'iceberg lettuce',
    'butter lettuce',
    'mixed greens',
    'spring mix',
    'swiss chard',
    'beet greens',
    'dandelion greens',
    'endive',
    'radicchio',
    'frisée',
    'escarole',

    // Vegetables - Stalks & Pods
    'celery',
    'asparagus',
    'artichoke',
    'fennel',
    'rhubarb',
    'bamboo shoots',
    'green beans',
    'french beans',
    'wax beans',
    'snap peas',
    'snow peas',
    'sugar snap peas',
    'peas',
    'edamame',
    'okra',

    // Vegetables - Others
    'corn',
    'corn on the cob',
    'baby corn',
    'mushrooms',
    'button mushrooms',
    'cremini mushrooms',
    'portobello mushrooms',
    'shiitake mushrooms',
    'oyster mushrooms',
    'enoki mushrooms',
    'morel mushrooms',
    'chanterelle mushrooms',
    'porcini mushrooms',
    'avocado',
    'hearts of palm',
    'water chestnuts',

    // Fruits - Citrus
    'lemon',
    'lime',
    'orange',
    'blood orange',
    'navel orange',
    'grapefruit',
    'tangerine',
    'mandarin',
    'clementine',
    'yuzu',
    'bergamot',
    'kumquat',

    // Fruits - Berries
    'strawberry',
    'blueberry',
    'raspberry',
    'blackberry',
    'cranberry',
    'lingonberry',
    'boysenberry',
    'elderberry',
    'gooseberry',
    'currants',
    'goji berries',

    // Fruits - Stone fruits
    'peach',
    'nectarine',
    'plum',
    'apricot',
    'cherry',
    'sweet cherry',
    'sour cherry',

    // Fruits - Tree fruits
    'apple',
    'granny smith apple',
    'honeycrisp apple',
    'gala apple',
    'fuji apple',
    'pear',
    'anjou pear',
    'bosc pear',
    'asian pear',
    'persimmon',
    'pomegranate',
    'fig',
    'fresh figs',
    'quince',

    // Fruits - Tropical
    'banana',
    'plantain',
    'pineapple',
    'mango',
    'papaya',
    'passion fruit',
    'guava',
    'kiwi',
    'dragon fruit',
    'star fruit',
    'lychee',
    'rambutan',
    'durian',
    'jackfruit',
    'coconut',
    'fresh coconut',

    // Fruits - Melons
    'watermelon',
    'cantaloupe',
    'honeydew',
    'casaba melon',
    'crenshaw melon',

    // Fruits - Grapes
    'grape',
    'red grapes',
    'green grapes',
    'black grapes',

    // Grains - Rice
    'rice',
    'white rice',
    'brown rice',
    'jasmine rice',
    'basmati rice',
    'arborio rice',
    'wild rice',
    'black rice',
    'red rice',
    'sushi rice',
    'rice noodles',
    'rice paper',

    // Grains - Wheat
    'flour',
    'all-purpose flour',
    'bread flour',
    'whole wheat flour',
    'cake flour',
    'semolina flour',
    'pasta',
    'spaghetti',
    'linguine',
    'fettuccine',
    'penne',
    'rigatoni',
    'fusilli',
    'farfalle',
    'lasagna sheets',
    'ravioli',
    'tortellini',
    'gnocchi',
    'bread',
    'white bread',
    'whole wheat bread',
    'sourdough bread',
    'rye bread',
    'pita bread',
    'naan bread',
    'bagels',
    'croissants',
    'baguette',

    // Grains - Other
    'quinoa',
    'barley',
    'pearl barley',
    'oats',
    'rolled oats',
    'steel cut oats',
    'oat flour',
    'couscous',
    'bulgur',
    'wheat berries',
    'farro',
    'spelt',
    'kamut',
    'millet',
    'amaranth',
    'buckwheat',
    'polenta',
    'cornmeal',
    'corn starch',
    'tapioca',
    'sago',

    // Noodles - Asian
    'noodles',
    'ramen noodles',
    'udon noodles',
    'soba noodles',
    'lo mein noodles',
    'chow mein noodles',
    'pad thai noodles',
    'glass noodles',
    'shirataki noodles',
    'bean thread noodles',

    // Dairy - Milk
    'milk',
    'whole milk',
    'skim milk',
    '2% milk',
    'buttermilk',
    'heavy cream',
    'half and half',
    'sour cream',
    'crème fraîche',
    'evaporated milk',
    'condensed milk',

    // Dairy - Cheese
    'cheese',
    'cheddar cheese',
    'mozzarella cheese',
    'swiss cheese',
    'provolone cheese',
    'monterey jack cheese',
    'pepper jack cheese',
    'american cheese',
    'parmesan cheese',
    'pecorino romano',
    'asiago cheese',
    'gruyere cheese',
    'gouda cheese',
    'brie cheese',
    'camembert cheese',
    'blue cheese',
    'roquefort cheese',
    'gorgonzola cheese',
    'feta cheese',
    'goat cheese',
    'ricotta cheese',
    'mascarpone cheese',
    'cream cheese',
    'cottage cheese',
    'string cheese',

    // Dairy - Other
    'butter',
    'unsalted butter',
    'salted butter',
    'yogurt',
    'greek yogurt',
    'plain yogurt',
    'vanilla yogurt',
    'kefir',

    // Plant-based alternatives
    'almond milk',
    'soy milk',
    'oat milk',
    'coconut milk',
    'cashew milk',
    'rice milk',
    'hemp milk',
    'nutritional yeast',
    'vegan butter',
    'coconut cream',

    // Oils & Fats
    'olive oil',
    'extra virgin olive oil',
    'vegetable oil',
    'canola oil',
    'sunflower oil',
    'safflower oil',
    'peanut oil',
    'sesame oil',
    'coconut oil',
    'avocado oil',
    'grapeseed oil',
    'walnut oil',
    'flaxseed oil',
    'lard',
    'duck fat',
    'ghee',
    'shortening',

    // Sweeteners
    'sugar',
    'white sugar',
    'brown sugar',
    'light brown sugar',
    'dark brown sugar',
    'powdered sugar',
    'raw sugar',
    'turbinado sugar',
    'coconut sugar',
    'palm sugar',
    'honey',
    'raw honey',
    'manuka honey',
    'maple syrup',
    'pure maple syrup',
    'agave nectar',
    'corn syrup',
    'molasses',
    'blackstrap molasses',
    'stevia',
    'erythritol',
    'xylitol',

    // Seasonings - Salt & Pepper
    'salt',
    'sea salt',
    'kosher salt',
    'himalayan pink salt',
    'flaky sea salt',
    'celery salt',
    'garlic salt',
    'onion salt',
    'black pepper',
    'white pepper',
    'pink peppercorns',
    'green peppercorns',
    'sichuan peppercorns',

    // Herbs - Fresh
    'basil',
    'fresh basil',
    'thai basil',
    'oregano',
    'fresh oregano',
    'thyme',
    'fresh thyme',
    'rosemary',
    'fresh rosemary',
    'parsley',
    'flat-leaf parsley',
    'curly parsley',
    'cilantro',
    'fresh cilantro',
    'mint',
    'fresh mint',
    'spearmint',
    'peppermint',
    'dill',
    'fresh dill',
    'sage',
    'fresh sage',
    'tarragon',
    'fresh tarragon',
    'chervil',
    'marjoram',
    'lemongrass',
    'kaffir lime leaves',

    // Herbs - Dried
    'dried basil',
    'dried oregano',
    'dried thyme',
    'dried rosemary',
    'dried parsley',
    'dried cilantro',
    'dried mint',
    'dried dill',
    'dried sage',
    'bay leaves',
    'dried tarragon',
    'herbs de provence',
    'italian seasoning',

    // Spices - Common
    'paprika',
    'sweet paprika',
    'smoked paprika',
    'cumin',
    'ground cumin',
    'coriander',
    'ground coriander',
    'turmeric',
    'ground turmeric',
    'ginger powder',
    'cinnamon',
    'ground cinnamon',
    'cinnamon sticks',
    'nutmeg',
    'ground nutmeg',
    'whole nutmeg',
    'allspice',
    'ground allspice',
    'cloves',
    'ground cloves',
    'whole cloves',
    'cardamom',
    'ground cardamom',
    'cardamom pods',
    'star anise',
    'fennel seeds',
    'caraway seeds',
    'celery seeds',
    'mustard seeds',
    'poppy seeds',
    'sesame seeds',
    'nigella seeds',

    // Spices - Hot
    'chili powder',
    'cayenne pepper',
    'red pepper flakes',
    'crushed red pepper',
    'chipotle powder',
    'ancho chili powder',
    'ghost pepper',
    'carolina reaper',

    // Spice Blends
    'curry powder',
    'garam masala',
    'tandoori masala',
    'chinese five spice',
    'za\'atar',
    'sumac',
    'harissa',
    'ras el hanout',
    'berbere',
    'cajun seasoning',
    'old bay seasoning',
    'taco seasoning',
    'jerk seasoning',
    'everything bagel seasoning',

    // Legumes - Beans
    'black beans',
    'kidney beans',
    'pinto beans',
    'navy beans',
    'great northern beans',
    'cannellini beans',
    'lima beans',
    'black-eyed peas',
    'garbanzo beans',
    'chickpeas',
    'adzuki beans',
    'mung beans',
    'fava beans',
    'cranberry beans',

    // Legumes - Lentils & Peas
    'lentils',
    'red lentils',
    'green lentils',
    'brown lentils',
    'black lentils',
    'french lentils',
    'split peas',
    'yellow split peas',
    'green split peas',

    // Nuts
    'almonds',
    'raw almonds',
    'roasted almonds',
    'sliced almonds',
    'almond flour',
    'walnuts',
    'pecans',
    'cashews',
    'pistachios',
    'hazelnuts',
    'brazil nuts',
    'macadamia nuts',
    'pine nuts',
    'chestnuts',
    'peanuts',
    'roasted peanuts',

    // Seeds
    'sunflower seeds',
    'pumpkin seeds',
    'pepitas',
    'chia seeds',
    'flax seeds',
    'hemp seeds',
    'sesame seeds',
    'tahini',
    'peanut butter',
    'almond butter',
    'cashew butter',
    'sunflower seed butter',

    // Condiments - Vinegars
    'vinegar',
    'white vinegar',
    'apple cider vinegar',
    'balsamic vinegar',
    'red wine vinegar',
    'white wine vinegar',
    'rice vinegar',
    'champagne vinegar',
    'sherry vinegar',
    'malt vinegar',

    // Condiments - Sauces
    'soy sauce',
    'low sodium soy sauce',
    'tamari',
    'worcestershire sauce',
    'fish sauce',
    'oyster sauce',
    'hoisin sauce',
    'teriyaki sauce',
    'sriracha',
    'hot sauce',
    'tabasco sauce',
    'chipotle sauce',
    'barbecue sauce',
    'ketchup',
    'mustard',
    'dijon mustard',
    'whole grain mustard',
    'yellow mustard',
    'mayonnaise',
    'aioli',
    'tahini',
    'hummus',
    'pesto',
    'chimichurri',
    'salsa',
    'salsa verde',
    'enchilada sauce',
    'marinara sauce',
    'tomato sauce',
    'alfredo sauce',
    'hollandaise sauce',
    'béarnaise sauce',

    // Canned/Jarred - Vegetables
    'canned tomatoes',
    'crushed tomatoes',
    'diced tomatoes',
    'whole tomatoes',
    'tomato paste',
    'tomato puree',
    'sun-dried tomatoes',
    'roasted red peppers',
    'artichoke hearts',
    'hearts of palm',
    'pickles',
    'dill pickles',
    'sweet pickles',
    'gherkins',
    'capers',
    'olives',
    'green olives',
    'black olives',
    'kalamata olives',
    'castelvetrano olives',
    'pitted olives',
    'stuffed olives',
    'olive tapenade',

    // Broths & Stocks
    'chicken broth',
    'beef broth',
    'vegetable broth',
    'mushroom broth',
    'bone broth',
    'chicken stock',
    'beef stock',
    'vegetable stock',
    'dashi',
    'miso paste',
    'bouillon cubes',

    // Baking ingredients
    'vanilla extract',
    'pure vanilla extract',
    'vanilla beans',
    'almond extract',
    'lemon extract',
    'rum extract',
    'baking powder',
    'baking soda',
    'cream of tartar',
    'active dry yeast',
    'instant yeast',
    'fresh yeast',
    'cocoa powder',
    'dark chocolate',
    'milk chocolate',
    'white chocolate',
    'chocolate chips',
    'mini chocolate chips',
    'dark chocolate chips',
    'white chocolate chips',
    'butterscotch chips',
    'coconut flakes',
    'shredded coconut',
    'unsweetened coconut',
    'sweetened coconut',
    'dried fruit',
    'raisins',
    'golden raisins',
    'dried cranberries',
    'dried cherries',
    'dried apricots',
    'dates',
    'medjool dates',
    'figs',
    'dried figs',

    // Grains for baking
    'panko breadcrumbs',
    'regular breadcrumbs',
    'graham crackers',
    'saltine crackers',
    'ritz crackers',

    // International specialty ingredients
    'mirin',
    'sake',
    'miso paste',
    'white miso',
    'red miso',
    'wakame',
    'nori',
    'kombu',
    'bonito flakes',
    'kimchi',
    'gochujang',
    'doenjang',
    'coconut milk',
    'coconut cream',
    'curry paste',
    'red curry paste',
    'green curry paste',
    'yellow curry paste',
    'massaman curry paste',
    'lemon grass',
    'galangal',
    'palm sugar',
    'tamarind paste',
    'shrimp paste',
    'black bean sauce',
    'doubanjiang',
    'shaoxing wine',
    'chinese black vinegar',
    'preserved lemons',
    'pomegranate molasses',
    'rose water',
    'orange blossom water',
    'saffron',
    'vanilla pods',
    'cardamom pods',
    'whole star anise',
    'whole cinnamon sticks',
    'whole cloves',
    'mace',
    'fenugreek',
    'asafoetida',
    'nigella seeds',
    'ajwain',
    'amchur',
    'chat masala',

    // Alcohol for cooking
    'white wine',
    'red wine',
    'sherry',
    'port wine',
    'marsala wine',
    'beer',
    'rum',
    'bourbon',
    'brandy',
    'cognac',
    'amaretto',
    'grand marnier',
    'cointreau',
    'kirsch',

    // Specialty dietary
    'gluten-free flour',
    'almond flour',
    'coconut flour',
    'rice flour',
    'chickpea flour',
    'tapioca flour',
    'arrowroot powder',
    'xanthan gum',
    'guar gum',
    'psyllium husk',
    'protein powder',
    'collagen powder',
  ];

  /// Filter ingredients based on search query
  static List<String> filterIngredients(String query) {
    if (query.isEmpty) return [];

    final lowercaseQuery = query.toLowerCase();

    return commonIngredients
        .where(
          (ingredient) => ingredient.toLowerCase().contains(lowercaseQuery),
        )
        .take(8) // Limit to 8 suggestions to avoid overwhelming UI
        .toList();
  }

  /// Check if an ingredient exists in the common list
  static bool isCommonIngredient(String ingredient) {
    return commonIngredients.any(
      (common) => common.toLowerCase() == ingredient.toLowerCase(),
    );
  }
}
