name: Staging Backend

on:
  push:
    branches: [dev]
    paths:
      - "backend/**"
  pull_request:
    branches: [dev]
    paths:
      - "backend/**"

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Run coverage tests
        run: npm run test:cov

      - name: Run linting
        run: npm run lint
